### ISSUE TITLE
FIXED: Add Hide / Show blocks for lists

### ISSUE THREAD

**Issue by htmlgames** [htmlgames/htmlgames.github.io#9]
A lot of project requests for this...

Please test your list project and give issues / feedback here...

**Comment by htmlgames** [comment]
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#168893734

**Comment by HelenaDj** [comment]
Yes, now list is showing, but nothing happens with that list, i.e. list elements should change the contents when some condition is met but that doesn't happen.

This refers to project:
Hangman
https://htmlgames.github.io/htmlgames/differences/UAT/itchy/index.html#168116502

**Comment by htmlgames** [comment]
Ok - I fixed now. Thanks for reporting.

**Comment by HelenaDj** [comment]
Great!!! It's working now! But now I have another problem and that is how to make application for android mobile phones. I pasted the id number of scratch project in the right place and packaged the project, then I copied the link from address bar and used Appsgeyser to create a apk file for the instalation. But when I installed the game from that apk file, game looks like picture in a attachment.
![screenshot_2017-09-12-08-16-15](https://user-images.githubusercontent.com/25203537/30314963-af949b98-97a2-11e7-92a0-498e38584f05.png)

If you can help me, it would be great! :)

**Comment by htmlgames** [comment]
(First, I have to update the base apk with the fix from this issue + other updates; please give me a few days for this)

ok, so all you need to do is follow the instructions from this post:

https://plus.google.com/+PaulFinnertys/posts/E1p9gxLRHEP

Note: the apk is only for Android devices running Lollipop and above

You shouldn't need any other software like Appsgeyser.

Please let me know how you get on in a few days. I'll create an apk of your project as well (as a test)

**Comment by HelenaDj** [comment]
Thank you for quick answer.
I'll wait for few days for you to come to the solution and then, if it isn't to much to ask, please explain in steps how you did it.
Thank you for your effort!

**Comment by htmlgames** [comment]
I've managed to recreate this issue now on my phone. Moved issue log here:

https://github.com/htmlgames/htmlgames.github.io/issues/13
